### ISSUE TITLE
Output is very visually cluttered and terminal width is not respected

### ISSUE THREAD

**Issue by Ben-Lichtman** [entropic-security/xgadget#2]
I think the dashes in the output make it very difficult to visually skim. Please could this be replaced with whitespace?

Also, it would appear that output is padded to around 15 characters in width no matter what. IMO this should be changed to print Address on one line then the gadget on the next, or potentially format the address depending on the width of the terminal window.

**Comment by Ben-Lichtman** [comment]
I did a bit of experimenting and I think formatting the output similar to ropper's output is much cleaner and easy to search through both visually and using grep etc.

<img width="Screenshot" src="https://user-images.githubusercontent.com/15235153/87411688-67678980-c60b-11ea-8405-5ea8ec51c484.png">

**Comment by tnballo** [comment]
Thought you'd shared `ropper` output until I noticed the red stack pointer! Appreciate both your suggestions and the time to prototype them. 2 points:

1. Rationale for the current formatting is supporting print of partial matches (same gadget, different program counter across `n` input binaries) while maintaining instruction alignment. Example where `n` is 2, notice binary name right of addr on partial match:

![partial_match](https://user-images.githubusercontent.com/24994892/87483568-0091a280-c602-11ea-8654-fc5e7909370a.png)

2. The fixed 150 character pad is due to use of a [format string here](https://github.com/entropic-security/xgadget/blob/0e7ac432ada11750875e48ab655a2e983bc0446a/src/main.rs#L199). Is there a way to generate the format string width parameter dynamically from terminal width? If not, can perform the formatting manually, as is [currently the case for colored output](https://github.com/entropic-security/xgadget/blob/0e7ac432ada11750875e48ab655a2e983bc0446a/src/main.rs#L187), but using a dynamic value. Agree respecting terminal width is the way to go!

@Ben-Lichtman what do you think about making `ropper`-style output the default when the partial match flag (`-m` or `--partial-match`) is *not* present (b/c 1 addr to print, e.g. single bin or cross-bin full match only)? If the flag is present, use the current style to maintain instruction alignment. And adjust for terminal width, but keep the green addr coloring (please). **Happy to work with you on a PR since you're already got it prototyped!**

That seems like best of both worlds, and creates an easier transition for new users coming off of other tools :smirk:

**Comment by Ben-Lichtman** [comment]
Would be happy to do a PR though I would probably move all of the formatting functionality out of the library and into the app so library consumers don’t have to take in the extra terminal colours crate. Does that sound acceptable?

Am a little busy lately but happy to make the PR later on.

**Comment by tnballo** [comment]
Absolutely no rush or obligation for a PR!

Would strongly prefer to stick with [the `colored` crate](https://crates.io/crates/colored) instead of re-implementing, since it's extremely popular and actively maintained. Figure that keeps this code base small/focused. And [binary releases](https://github.com/entropic-security/xgadget/releases) compile it in, so there's no portability issues I'm aware of - just one extra lib to pull in for users building from source.

**Comment by tnballo** [comment]
It's been a little while so I wanted to close the loop on this issue. Latest (`0.2.0`) version defaults to `ropper`-style output as you've suggested:

![2020-10-17-172540_2558x506_scrot](https://user-images.githubusercontent.com/24994892/96354166-77c35080-10a1-11eb-9274-5fdf541adad4.png)

But if `-e`/`--extended-fmt` or `-m`/`--partial-match` is present, uses the previous stye - **which now respects terminal width**! Used crate [`term_size`](https://crates.io/crates/term_size).

![2020-10-17-172658_2557x874_scrot](https://user-images.githubusercontent.com/24994892/96354168-7db93180-10a1-11eb-8a3e-6866bd6a9198.png)

Sped up printing speed for the latter by building the string and then printing it once, instead of printing each dash individually in a tight loop (derp).

Thanks for opening this issue! Saw that you're working on a gadget finder inspired by this one ([`ropr`](https://github.com/Ben-Lichtman/ropr)) - that's awesome! :smiley:
